//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodaholics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogContent
    {
        public int id { get; set; }
        public int BlogID { get; set; }
        public string Value { get; set; }
        public string Feedback { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
