//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodaholics.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodaholicDBEntities : DbContext
    {
        public FoodaholicDBEntities()
            : base("name=FoodaholicDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlogComment> BlogComments { get; set; }
        public virtual DbSet<BlogContent> BlogContents { get; set; }
        public virtual DbSet<BlogImage> BlogImages { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<User> Users { get; set; }

        public System.Data.Entity.DbSet<Foodaholics.Models.UpdatePassword> UpdatePasswords { get; set; }

        public System.Data.Entity.DbSet<Foodaholics.Models.ShowBlog> ShowBlogs { get; set; }

        public System.Data.Entity.DbSet<Foodaholics.Models.WriteBlog> WriteBlogs { get; set; }

        public System.Data.Entity.DbSet<Foodaholics.Models.BlogDetails> BlogDetails { get; set; }
    }
}
